/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx}'],
  darkMode: ['class', '[data-theme="dark"]'],
  theme: {
    extend: {
      colors: {
        ink: 'var(--c-ink)',
        'ink-soft': 'var(--c-ink-soft)',
        body: 'var(--c-body)',
        paper: 'var(--c-paper)',
        surface: 'var(--c-surface)',
        saffron: 'var(--c-saffron)',
        'saffron-deep': 'var(--c-saffron-deep)',
        clay: 'var(--c-clay)',
        sage: 'var(--c-sage)',
        line: 'var(--c-line)',
        success: 'var(--c-success)',
        'on-ink': 'var(--c-on-ink)',
        'on-saffron': 'var(--c-on-saffron)',
      },
      spacing: {
        1: 'var(--space-1)',
        2: 'var(--space-2)',
        3: 'var(--space-3)',
        4: 'var(--space-4)',
        5: 'var(--space-5)',
        6: 'var(--space-6)',
        7: 'var(--space-7)',
        8: 'var(--space-8)',
        9: 'var(--space-9)',
        10: 'var(--space-10)',
      },
      borderRadius: {
        sm: 'var(--radius-sm)',
        DEFAULT: 'var(--radius-sm)',
        md: 'var(--radius-md)',
        lg: 'var(--radius-md)',
      },
      fontSize: {
        xs: 'var(--text-xs)',
        sm: 'var(--text-sm)',
        base: 'var(--text-base)',
        md: 'var(--text-md)',
        lg: 'var(--text-lg)',
        xl: 'var(--text-xl)',
        '2xl': 'var(--text-2xl)',
        '3xl': 'var(--text-3xl)',
        '4xl': 'var(--text-4xl)',
      },
      fontFamily: {
        'ar-display': 'var(--font-ar-display)',
        'ar-body': 'var(--font-ar-body)',
        'en-display': 'var(--font-en-display)',
        'en-body': 'var(--font-en-body)',
      },
      boxShadow: {
        none: 'none',
        focus: 'var(--shadow-focus)',
      },
    },
  },
  plugins: [],
};
